In [2]:
import pandas as pd
import numpy as np
data=pd.read_csv('Mall_Customers.csv')
data.head()

CustomerID   Genre  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [4]:
X=data.iloc[:,:-1].values
Y=data.iloc[:,4].values

# Label Encoding

In [18]:
from  sklearn.preprocessing import LabelEncoder
lbl=LabelEncoder()
X[:,1]=lbl.fit_transform(X[:,1])
X

array([[1, 1, 19, 15],
       [2, 1, 21, 15],
       [3, 0, 20, 16],
       [4, 0, 23, 16],
       [5, 0, 31, 17],
       [6, 0, 22, 17],
       [7, 0, 35, 18],
       [8, 0, 23, 18],
       [9, 1, 64, 19],
       [10, 0, 30, 19],
       [11, 1, 67, 19],
       [12, 0, 35, 19],
       [13, 0, 58, 20],
       [14, 0, 24, 20],
       [15, 1, 37, 20],
       [16, 1, 22, 20],
       [17, 0, 35, 21],
       [18, 1, 20, 21],
       [19, 1, 52, 23],
       [20, 0, 35, 23],
       [21, 1, 35, 24],
       [22, 1, 25, 24],
       [23, 0, 46, 25],
       [24, 1, 31, 25],
       [25, 0, 54, 28],
       [26, 1, 29, 28],
       [27, 0, 45, 28],
       [28, 1, 35, 28],
       [29, 0, 40, 29],
       [30, 0, 23, 29],
       [31, 1, 60, 30],
       [32, 0, 21, 30],
       [33, 1, 53, 33],
       [34, 1, 18, 33],
       [35, 0, 49, 33],
       [36, 0, 21, 33],
       [37, 0, 42, 34],
       [38, 0, 30, 34],
       [39, 0, 36, 37],
       [40, 0, 20, 37],
       [41, 0, 65, 38],
       [42, 1, 24, 38],
 

In [8]:
# female values encoded as 0 and male values as 1

## train_test_split

In [72]:
df=pd.read_csv('income_evaluation.csv')
df.head()

age          workclass   fnlwgt   education   education-num  \
0   39          State-gov    77516   Bachelors              13   
1   50   Self-emp-not-inc    83311   Bachelors              13   
2   38            Private   215646     HS-grad               9   
3   53            Private   234721        11th               7   
4   28            Private   338409   Bachelors              13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

    capital-gain   capital-loss   hours-per-week  native-country  income  
0           2174              0               40   United-States   <=50K  
1              0              0               13   United-States   <=50K  
2              0              0               40   United-States   <=50K  
3              0              0               40   United-States   <=50K  
4              0              0               40            Cuba   <=50K

In [73]:
df.shape

(32561, 15)

In [75]:
df.sample()

age  workclass   fnlwgt   education   education-num  marital-status  \
22154   42    Private   336643   Assoc-voc              11       Separated   

            occupation  relationship    race      sex   capital-gain  \
22154   Prof-specialty     Unmarried   White   Female              0   

        capital-loss   hours-per-week  native-country  income  
22154              0               40   United-States   <=50K

In [76]:
df.sample(2)

age  workclass   fnlwgt     education   education-num  \
26319   46    Private   175625   Prof-school              15   
10127   45    Private    34248       HS-grad               9   

            marital-status       occupation  relationship    race      sex  \
26319             Divorced   Prof-specialty     Unmarried   White   Female   
10127   Married-civ-spouse            Sales       Husband   White     Male   

        capital-gain   capital-loss   hours-per-week  native-country  income  
26319              0              0               40   United-States   <=50K  
10127              0              0               50   United-States   <=50K

In [79]:
df=df.sample(frac=1)
df

age          workclass   fnlwgt      education   education-num  \
24694   17                  ?   145258           11th               7   
3061    40            Private   245529     Assoc-acdm              12   
19188   27            Private   182540           11th               7   
193     47            Private   120939   Some-college              10   
11351   49       Self-emp-inc   201498        HS-grad               9   
...    ...                ...      ...            ...             ...   
19035   26            Private   285004      Bachelors              13   
23804   48   Self-emp-not-inc   243631        HS-grad               9   
13424   38            Private   226106   Some-college              10   
14421   67            Private   180539        HS-grad               9   
10025   45          Local-gov   102359      Bachelors              13   

            marital-status        occupation     relationship  \
24694        Never-married                 ?   Other-relative   
3061              Divorced    Prof-specialty    Not-in-family   
19188        Never-married      Craft-repair    Not-in-family   
193     Married-civ-spouse      Tech-support          Husband   
11351   Married-civ-spouse      Craft-repair          Husband   
...                    ...               ...              ...   
19035        Never-married   Exec-managerial    Not-in-family   
23804   Married-civ-spouse   Exec-managerial          Husband   
13424        Never-married      Adm-clerical        Unmarried   
14421   Married-civ-spouse             Sales          Husband   
10025   Married-civ-spouse    Prof-specialty          Husband   

                      race      sex   capital-gain   capital-loss  \
24694                White   Female              0              0   
3061                 White   Female              0              0   
19188                White     Male              0              0   
193                  White     Male              0              0   
11351                White     Male              0              0   
...                    ...      ...            ...            ...   
19035   Asian-Pac-Islander     Male              0              0   
23804   Asian-Pac-Islander     Male              0              0   
13424                Black   Female              0              0   
14421                White     Male              0              0   
10025                White     Male              0              0   

        hours-per-week  native-country  income  
24694               25   United-States   <=50K  
3061                40   United-States   <=50K  
19188               40   United-States   <=50K  
193                 45   United-States   <=50K  
11351               40   United-States   <=50K  
...                ...             ...     ...  
19035               35           South   <=50K  
23804               30           South   <=50K  
13424               40   United-States   <=50K  
14421               10   United-States   <=50K  
10025               37   United-States   <=50K  

[32561 rows x 15 columns]

In [80]:
len(df)*0.8

26048.800000000003

In [81]:
df[:26048]

age          workclass   fnlwgt      education   education-num  \
24694   17                  ?   145258           11th               7   
3061    40            Private   245529     Assoc-acdm              12   
19188   27            Private   182540           11th               7   
193     47            Private   120939   Some-college              10   
11351   49       Self-emp-inc   201498        HS-grad               9   
...    ...                ...      ...            ...             ...   
26209   32            Private   255885      Bachelors              13   
26876   32          State-gov   400132      Bachelors              13   
6255    53   Self-emp-not-inc   152810           10th               6   
9284    23            Private   109952   Some-college              10   
19182   53            Private   290640        HS-grad               9   

            marital-status        occupation     relationship    race  \
24694        Never-married                 ?   Other-relative   White   
3061              Divorced    Prof-specialty    Not-in-family   White   
19188        Never-married      Craft-repair    Not-in-family   White   
193     Married-civ-spouse      Tech-support          Husband   White   
11351   Married-civ-spouse      Craft-repair          Husband   White   
...                    ...               ...              ...     ...   
26209   Married-civ-spouse   Exec-managerial          Husband   White   
26876   Married-civ-spouse   Protective-serv          Husband   White   
6255    Married-civ-spouse      Craft-repair          Husband   White   
9284    Married-civ-spouse      Craft-repair          Husband   White   
19182   Married-civ-spouse     Other-service          Husband   White   

           sex   capital-gain   capital-loss   hours-per-week  native-country  \
24694   Female              0              0               25   United-States   
3061    Female              0              0               40   United-States   
19188     Male              0              0               40   United-States   
193       Male              0              0               45   United-States   
11351     Male              0              0               40   United-States   
...        ...            ...            ...              ...             ...   
26209     Male              0              0               43   United-States   
26876     Male              0              0               40   United-States   
6255      Male              0              0               40   United-States   
9284      Male              0              0               60   United-States   
19182     Male              0              0               50         Germany   

       income  
24694   <=50K  
3061    <=50K  
19188   <=50K  
193     <=50K  
11351   <=50K  
...       ...  
26209    >50K  
26876    >50K  
6255    <=50K  
9284    <=50K  
19182    >50K  

[26048 rows x 15 columns]

In [82]:
train=df[:26048]
test=df[26048:]


In [92]:
#to remove space we can:
train.columns=train.columns.str.lstrip()
test.columns=test.columns.str.lstrip()


In [93]:
X_train=train.drop('income',axis=1)

In [86]:
X_train.head()

age      workclass   fnlwgt      education   education-num  \
24694   17              ?   145258           11th               7   
3061    40        Private   245529     Assoc-acdm              12   
19188   27        Private   182540           11th               7   
193     47        Private   120939   Some-college              10   
11351   49   Self-emp-inc   201498        HS-grad               9   

            marital-status       occupation     relationship    race      sex  \
24694        Never-married                ?   Other-relative   White   Female   
3061              Divorced   Prof-specialty    Not-in-family   White   Female   
19188        Never-married     Craft-repair    Not-in-family   White     Male   
193     Married-civ-spouse     Tech-support          Husband   White     Male   
11351   Married-civ-spouse     Craft-repair          Husband   White     Male   

        capital-gain   capital-loss   hours-per-week  native-country  
24694              0              0               25   United-States  
3061               0              0               40   United-States  
19188              0              0               40   United-States  
193                0              0               45   United-States  
11351              0              0               40   United-States

In [94]:
y_train=train.income

In [95]:
y_train

24694     <=50K
3061      <=50K
19188     <=50K
193       <=50K
11351     <=50K
          ...  
26209      >50K
26876      >50K
6255      <=50K
9284      <=50K
19182      >50K
Name: income, Length: 26048, dtype: object

In [98]:
X_test=test.drop('income',axis='columns')

In [100]:
y_test=test.income


## second method to test and train data from sk learn library

In [101]:
d=pd.read_csv('income_evaluation.csv')
d.head()

age          workclass   fnlwgt   education   education-num  \
0   39          State-gov    77516   Bachelors              13   
1   50   Self-emp-not-inc    83311   Bachelors              13   
2   38            Private   215646     HS-grad               9   
3   53            Private   234721        11th               7   
4   28            Private   338409   Bachelors              13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

    capital-gain   capital-loss   hours-per-week  native-country  income  
0           2174              0               40   United-States   <=50K  
1              0              0               13   United-States   <=50K  
2              0              0               40   United-States   <=50K  
3              0              0               40   United-States   <=50K  
4              0              0               40            Cuba   <=50K

In [105]:
from sklearn.model_selection import train_test_split

X1_train,X2_test,y1_train,y2_test=train_test_split(d.drop(' income',axis=1),d[' income'],test_size=0.2,random_state=0,stratify=d[' income'])

In [106]:
y1_train.value_counts()

 <=50K    19775
 >50K      6273
Name:  income, dtype: int64

In [107]:
y2_test.value_counts()

 <=50K    4945
 >50K     1568
Name:  income, dtype: int64

In [108]:
d[' income'].value_counts()

 <=50K    24720
 >50K      7841
Name:  income, dtype: int64

In [109]:
7841*0.2

1568.2

In [110]:
7841*0.8

6272.8

In [112]:
24720*0.8

19776.0

In [113]:
24720*0.2

4944.0

## Label Encoding

In [22]:
# 2nd dataset for label encoder

In [25]:
df=pd.read_csv('income_evaluation.csv')
df.head()

age          workclass   fnlwgt   education   education-num  \
0   39          State-gov    77516   Bachelors              13   
1   50   Self-emp-not-inc    83311   Bachelors              13   
2   38            Private   215646     HS-grad               9   
3   53            Private   234721        11th               7   
4   28            Private   338409   Bachelors              13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

    capital-gain   capital-loss   hours-per-week  native-country  income  
0           2174              0               40   United-States   <=50K  
1              0              0               13   United-States   <=50K  
2              0              0               40   United-States   <=50K  
3              0              0               40   United-States   <=50K  
4              0              0               40            Cuba   <=50K

In [97]:
df[' income'].value_counts()

 <=50K    24720
 >50K      7841
Name:  income, dtype: int64

In [27]:
from sklearn.model_selection import train_test_split

In [35]:
X_train,X_test,y_train,y_test=train_test_split(df.drop(' income',axis=1),df[' income'],test_size=0.2,random_state=0)

In [36]:
from sklearn.preprocessing import LabelEncoder

In [37]:
le=LabelEncoder()
le.fit(y_train)

LabelEncoder()

In [39]:
le.classes_

array([' <=50K', ' >50K'], dtype=object)

In [40]:
le.transform(y_train)

array([0, 0, 0, ..., 0, 1, 0])

In [42]:
pd.Series(le.transform(y_train))

0        0
1        0
2        0
3        0
4        0
        ..
26043    1
26044    0
26045    0
26046    1
26047    0
Length: 26048, dtype: int32

In [43]:
le.transform(y_test)

array([0, 0, 0, ..., 1, 0, 1])

In [46]:
X_train[' native-country']

15282     United-States
24870     United-States
18822     United-States
26404     United-States
7842      United-States
              ...      
13123     United-States
19648     United-States
9845      United-States
10799     United-States
2732      United-States
Name:  native-country, Length: 26048, dtype: object

In [47]:
lb=LabelEncoder()
lb.fit_transform(X_train[' native-country'])
#lb.transform(X_train[' native-country'])

array([39, 39, 39, ..., 39, 39, 39])

In [49]:
pd.Series(lb.fit_transform(X_train[' native-country']))

0        39
1        39
2        39
3        39
4        39
         ..
26043    39
26044    39
26045    39
26046    39
26047    39
Length: 26048, dtype: int32

In [51]:
# we should not include label encoder for native-country as it randomly assign the numerical values and assigning numbers based on 
#alphabetical order and cause biasness gto ml model

## Ordinal Encoder

In [52]:
# can be used to encode categorical features

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(df.drop(' income',axis=1),df[' income'],test_size=0.2,random_state=0)

In [55]:
X_train[' education'].value_counts()

 HS-grad         8450
 Some-college    5832
 Bachelors       4242
 Masters         1414
 Assoc-voc       1110
 11th             920
 Assoc-acdm       817
 10th             752
 7th-8th          526
 Prof-school      459
 9th              419
 12th             360
 Doctorate        306
 5th-6th          259
 1st-4th          139
 Preschool         43
Name:  education, dtype: int64

In [57]:
X_train[' education'].unique()

array([' 11th', ' HS-grad', ' Bachelors', ' Assoc-voc', ' Some-college',
       ' 9th', ' 10th', ' 12th', ' Doctorate', ' Prof-school', ' Masters',
       ' Assoc-acdm', ' 7th-8th', ' 5th-6th', ' Preschool', ' 1st-4th'],
      dtype=object)

In [58]:
ed = [' Preschool', ' 1st-4th', ' 5th-6th', ' 7th-8th', ' 9th', ' 10th',
       ' 11th', ' 12th', ' HS-grad', ' Prof-school', ' Some-college',
       ' Assoc-acdm', ' Assoc-voc',' Bachelors', ' Masters', ' Doctorate' ]

In [67]:
gen=[' Male',' Female']

In [69]:
from sklearn.preprocessing import OrdinalEncoder
ordi=OrdinalEncoder(categories=[ed,gen])
ordi.fit(X_train[[' education',' sex']])



OrdinalEncoder(categories=[[' Preschool', ' 1st-4th', ' 5th-6th', ' 7th-8th',
                            ' 9th', ' 10th', ' 11th', ' 12th', ' HS-grad',
                            ' Prof-school', ' Some-college', ' Assoc-acdm',
                            ' Assoc-voc', ' Bachelors', ' Masters',
                            ' Doctorate'],
                           [' Male', ' Female']])

In [70]:
pd.DataFrame(ordi.transform(X_train[[' education',' sex']]))

0    1
0       6.0  0.0
1       8.0  1.0
2      13.0  1.0
3       8.0  1.0
4      12.0  0.0
...     ...  ...
26043  14.0  0.0
26044   5.0  0.0
26045  10.0  1.0
26046  15.0  0.0
26047  10.0  0.0

[26048 rows x 2 columns]

In [71]:
ordi.transform(X_test[[' education',' sex']])

array([[10.,  1.],
       [13.,  1.],
       [11.,  0.],
       ...,
       [13.,  0.],
       [ 8.,  0.],
       [ 8.,  0.]])

# One Hot Encoding

In [111]:
from sklearn.preprocessing import OneHotEncoder
onehotencod = OneHotEncoder(categorical_features=[1] )
X = onehotencod.fit_transform(X).toarray()
X

TypeError: __init__() got an unexpected keyword argument 'categorical_features'